### ISSUE TITLE
Knapsack problem using Greedy Approach in java

### ISSUE THREAD

**Issue by riteshyadav27** [Kavya-24/Snippets#260]
@Kavya-24 I want to add Knapsack problem using Greedy Approach in java in Algorithm . Please Assign me this task and add a label of hacktoberfest.

**Comment by Kavya-24** [comment]
@riteshyadav27 go ahead

**Comment by riteshyadav27** [comment]
I have added the file . You can check it If there is any need to update then let me know.
Will you please add hacktoberfest label 🙌

**Comment by Kavya-24** [comment]
Merged by #261 
Closed by #261 
Great work @riteshyadav27 :)

**Comment by riteshyadav27** [comment]
Thank You !!
