### ISSUE TITLE
QA: `Contributing Guidelines` Missing

### ISSUE THREAD

**Issue by Aryamanz29** [Kavya-24/Snippets#62]
- Currently, there is no `CONTRIBUTING.md` in the project

**Comment by Aryamanz29** [comment]
I want to work on this @Kavya-24

**Comment by Aryamanz29** [comment]
@Kavya-24  Please add review PR and add hacktoberfest labels
Thanks

**Comment by Kavya-24** [comment]
Sure @Aryamanz29 Go ahead :)
